services:
  drone-srcb:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      TG_BOT_TOKEN: $BOT_TOKEN
      AUTH_USERS: $AUTH_USERS_ID
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
